[[redirects]]
  from = "/gaza-response"
  to = "https://donorbox.org/help-distribute-aid-save-humans-in-gaza"
  status = 302
  force = true

[[redirects]]
  from = "/send-aid-to-gaza"
  to = "https://donorbox.org/help-distribute-aid-save-humans-in-gaza"
  status = 302
  force = true

[[redirects]]
  from = "/donate-now"
  to = "https://www.omprakash.org/global/distribute-aid/donate"
  status = 302
  force = true

[[redirects]]
  from = "/hurricane-response"
  to = "https://www.omprakash.org/global/distribute-aid/crowdfund/grassroots-response-to-hurricane-helene"
  status = 302
  force = true
