instagram_url: 'https://www.instagram.com/distributeaid'
twitter_url: 'https://twitter.com/DistributeAid'
linkedin_url: 'https://www.linkedin.com/company/distribute-aid'
facebook_url: 'https://www.facebook.com/DistributeAidDotOrg/'
footer_email: 'hello@distributeaid.org'
