name: 🐛 Bug Report
description: Report a bug to help improve our project.
labels: ['bug', 'triage']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is. Also tell us, what did you expect to happen?
      placeholder: Tell us what you see.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the error. Ideally provide screenshots of the problem.
      placeholder: 1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/distributeaid/.github/blob/saga/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
