name: Ensure source code is properly formatted

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Format source code with prettier
        run: npx prettier --write ./

      - name: Commit changes
        run: |
          if ! git diff --exit-code --name-only; then
            echo "machine github.com login accesskey password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
            git config --global user.email "actions@example.com"
            git config --global user.name "github-actions[bot]"
            git add -A
            git commit -m "style: auto-format source code"
            git push
          fi
